### ISSUE TITLE
I get jquery.cloudinary.js not cloudinary.js

### ISSUE THREAD

**Issue by ORESoftware** [cloudinary/bower-cloudinary#1]
hi all

when I run

$ bower install cloudinary

I get

cloudinary/js/canvas-to-blob.js
cloudinary/js/jquery.cloudinary.js
cloudinary/js/load-image.all.min.js

but I thought I was getting

cloudinary/js/cloudinary.js

did I do something wrong? (most likely)?

thanks

**Comment by taragano** [comment]
Hi @ORESoftware,
As mentioned in this repository's [Readme file](https://github.com/cloudinary/bower-cloudinary/blob/master/README.md), the sources for this repository are maintained at the `cloudinary_js` repository as it is the one that's constantly updated, and you should use that instead of this (`bower-cloudinary`) repository.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
